app/assets/javascripts/private_label/application.js, app/assets/stylesheets/private_label/application.css.scss, app/helpers/private_label/application_helper.rb, app/views/private_label/homepage/show.html.erb, app/views/private_label/layouts/_single_column.html.erb, app/views/private_label/layouts/application.html.erb, app/views/private_label/shared/modals/_login.html.erb
Added modals and fixed main content area to not require content_for
=> Added in login modals

app/models/person.rb, db/migrate/20150120023814_add_admin_to_private_label_people.rb, db/schema.rb
The PrivateLabelAdministrators join model has been consolidated into the PrivateLabelPeople join model.
=> Update join table associations on Person model

spec/controllers/private_labels/users_controller_spec.rb
http://media.tumblr.com/1e1d8ecea26aa3ce4e442c713e1e6004/tumblr_inline_mok7jhHaaZ1qz4rgp.png
=> Fix PeopleController spec

app/assets/stylesheets/private_label/main.css.scss, app/controllers/private_labels/search_controller.rb, app/helpers/private_labels/application_helper.rb, app/models/contribution.rb, app/models/conversation.rb, app/views/private_labels/search/_contribution.html.erb, app/views/private_labels/search/_conversation.html.erb, app/views/private_labels/search/_hit.html.erb, app/views/private_labels/search/results.html.erb, spec/helpers/private_labels/application_helper_spec.rb
Add search functionality to the site. - will break unless you merge in my other pull request. https://github.com/CivicCommons/CivicCommons/pull/32
=> Pl 88 search

app/controllers/private_labels/application_controller.rb, app/controllers/private_labels/contributions_controller.rb, app/controllers/private_labels/conversations_controller.rb, app/controllers/private_labels/homepage_controller.rb, app/controllers/private_labels/people_controller.rb, app/controllers/private_labels/search_controller.rb
specs will fail because the admin controllers sill call PlController
=> rename PlController to ApplicationController

app/concerns/private_label_controller_concern.rb, app/controllers/private_labels/admin/base_controller.rb, app/controllers/private_labels/admin/contributions_controller.rb, app/controllers/private_labels/admin/conversations_controller.rb, app/controllers/private_labels/admin/dashboard_controller.rb, app/controllers/private_labels/admin/people_controller.rb, app/controllers/private_labels/contributions_controller.rb, app/controllers/private_labels/homepage_controller.rb, app/controllers/private_labels/people_controller.rb, app/controllers/private_labels/registrations_controller.rb, app/controllers/private_labels/search_controller.rb, app/models/swayze.rb, app/views/private_labels/admin/dashboard/show.html.erb, app/views/private_labels/conversations/show.html.erb, app/views/private_labels/registrations/_tos.html.erb, spec/controllers/private_labels/homepage_controller_spec.rb, spec/models/swayze_spec.rb
Updates to the calls to Swayze.
=> Pl swayze changes

app/controllers/private_labels/admin/private_label_people_controller.rb
I realized that I need to sort the list of people that are displayed.
=> Sort people by last name and then first name

spec/controllers/private_labels/admin/conversations_controller_spec.rb
- Title for conversation could be longer than is valid, thus making the
spec fail
- Add specs for when the conversation doesn't save
=> Fix failing spec

app/assets/stylesheets/private_label/admin.css.scss, app/assets/stylesheets/private_label/header.css.scss, app/controllers/private_labels/admin/pages_controller.rb, app/controllers/private_labels/pages_controller.rb, app/helpers/private_labels/application_helper.rb, app/models/private_labels/page.rb, app/views/private_labels/admin/pages/_form.html.erb, app/views/private_labels/admin/pages/edit.html.erb, app/views/private_labels/admin/pages/index.html.erb, app/views/private_labels/admin/pages/new.html.erb, app/views/private_labels/layouts/application.html.erb, app/views/private_labels/pages/show.html.erb, app/views/private_labels/shared/_header.html.erb, app/views/private_labels/shared/_meta_tags.html.erb, config/initializers/date_formats.rb
Updated to add pages to the navigation, and style them a bit.
=> Pl 95 page manager

app/assets/stylesheets/private_label/admin.css.scss, app/helpers/private_labels/application_helper.rb, app/views/private_labels/admin/conversations/index.html.erb, app/views/private_labels/admin/pages/index.html.erb, app/views/private_labels/admin/private_label/show.html.erb, app/views/private_labels/admin/private_label_people/index.html.erb, app/views/private_labels/admin/sidebars/edit.html.erb, spec/helpers/private_labels/application_helper_spec.rb
Just some polishy things for the private label admin pages to improve consistency.
=> Pl polishing

app/assets/stylesheets/private_label/theme.css.scss, app/controllers/private_labels/admin/private_label_controller.rb, app/models/private_label.rb, app/views/private_labels/admin/private_label/edit.html.erb, app/views/private_labels/admin/shared/_sidebar.html.erb, app/views/private_labels/layouts/application.html.erb, config/routes.rb, spec/controllers/private_labels/admin/private_label_controller_spec.rb, spec/models/private_label_spec.rb
Add support for selecting color theme for private label
- Allow access to theme value on private label model
- Set body tag CSS class based on theme
- Add theme selection to private label settings form
=> Pl add theme to form

app/assets/stylesheets/private_label/admin.css.scss, app/assets/stylesheets/private_label/content-area.css.scss, app/assets/stylesheets/private_label/header.css.scss, app/assets/stylesheets/private_label/sidebar.css.scss, app/controllers/private_labels/admin/pages_controller.rb, app/controllers/private_labels/contributions_controller.rb, app/controllers/private_labels/homepage_controller.rb, app/models/private_labels/page.rb, app/views/private_labels/admin/conversations/_form.html.erb, app/views/private_labels/admin/conversations/index.html.erb, app/views/private_labels/admin/pages/_form.html.erb, app/views/private_labels/conversations/partials/_conversation_content.html.erb, app/views/private_labels/homepage/show.html.erb, app/views/private_labels/shared/_header.html.erb, app/views/private_labels/shared/_sidebar.html.erb, db/migrate/20110720172430_collapse_contribution_hierarchy.rb, db/migrate/20150210144447_add_is_home_to_private_labels_pages.rb, db/schema.rb, lib/private_labels/ability.rb
Fix the sidebar, show images in conversations
=> cleanup items

app/views/private_labels/admin/conversations/_form.html.erb, app/views/private_labels/admin/pages/_form.html.erb, app/views/private_labels/admin/private_label/edit.html.erb
The labels in Private Label admin were wrapping, so I've made that column a bit bigger, and made the other column a bit smaller to compensate.
=> Provide the labels more room to avoid wrapping

app/views/private_labels/admin/conversations/_form.html.erb, app/views/private_labels/admin/pages/_form.html.erb, app/views/private_labels/admin/private_label/edit.html.erb, app/views/private_labels/admin/sidebars/edit.html.erb
Add helpful text and tweak field labels in Private Label Admin to clarify what is needed.
=> 136 form help

app/controllers/private_labels/admin/private_label_controller.rb, app/models/private_label.rb, app/views/private_labels/admin/private_label/edit.html.erb, spec/controllers/private_labels/admin/private_label_controller_spec.rb
The errors messages on the form still need to be styled; I'm adding a separate card for that.
=> Pl 149 image validation

.ruby-style.yml, app/controllers/private_labels/homepage_controller.rb, app/mailers/private_labels/contact.rb, app/models/private_labels/contact_us_message.rb, app/views/layouts/plain_email.html.erb, app/views/private_labels/contact/send_contact_email.html.erb, app/views/private_labels/homepage/partials/_contact_form.html.erb, spec/controllers/private_labels/homepage_controller_spec.rb
When a contact form is submitted on a private label a simple HTMl email will be sent. 
It is sent to the email contact on the private label.
=> Send simple email from PL Contact Form

app/views/private_labels/admin/private_label/edit.html.erb
=> Added additional description to the main image on the admin side for PL

app/assets/stylesheets/application.css, app/views/private_labels/shared/_footer.html.erb, db/schema.rb
https://trello.com/c/47V6Uzb7/182-private-label-bug-footer-link-style
Added upcase to footer links
=> add auto upcasing footer links for pages

app/assets/stylesheets/private_label/content-area.css.scss, app/assets/stylesheets/private_label/main.css.scss, app/assets/stylesheets/private_label/variables.css.scss, app/helpers/private_labels/admin_helper.rb, app/helpers/private_labels/application_helper.rb, app/models/private_label.rb, app/views/private_labels/admin/dashboard/show.html.erb, app/views/private_labels/admin/private_label/edit.html.erb, app/views/private_labels/homepage/contact.html.erb, config/initializers/field_error_proc.rb, config/routes.rb, lib/private_label_domain_validator.rb, spec/factories/private_label_factory.rb
Fixed a number of display bugs and formatting for settings and contact us.
=> Private Label Admin:  Support settings

app/controllers/private_labels/user_controller.rb, app/helpers/private_labels/admin_helper.rb, app/views/private_labels/admin/dashboard/show.html.erb, app/views/private_labels/user/edit.html.erb, app/views/private_labels/user/show.html.erb, config/routes.rb, spec/controllers/private_labels/user_controller_spec.rb
https://trello.com/c/Y9Blnk10/177-private-label-bug-account-404
Added Private Label User Controller
Added Routes for said controller
Added Views for said routes from said controller
Added Basic Styling
=> Pl 177 account links

app/views/private_labels/registrations/new.html.erb, app/views/private_labels/shared/modals/_login.html.erb
Changed host on social log ins
=> changed host on social logins

app/assets/stylesheets/private_label/theme.css.scss, app/views/private_labels/user/edit.html.erb
- Changed labels to match theme
- Added spacing between rows
- Made button match theme
- Corrected alignment on all inputs
=> Bug/188 User Edit Style

app/controllers/private_labels/admin/conversations_controller.rb, config/routes.rb
https://trello.com/c/n4WuKmNf/192-private-label-bug-convo-delete
- Added controller function to destroy a conversation
- Added route to controller
=> Bug/192 Delete Conversation

app/views/private_labels/contributions/_contribution.html.erb
https://trello.com/c/DaeO0IsK/187-private-label-ux-user-image
- Switched image to use current_person image
=> Bug/187 Contribution Image

app/controllers/private_labels/admin/private_label_controller.rb
Added a fairly generic error message when saving the pl
=> Added a flash notice when validation errors prevent saving the PL

app/controllers/private_labels/confirmations_controller.rb, app/controllers/private_labels/passwords_controller.rb, app/views/private_labels/confirmations/new.html.erb, app/views/private_labels/passwords/new.html.erb, config/routes.rb
Added controller and views for Password Reset and Account Confirmation in private label
=> Pl forgot password

app/views/private_labels/user/edit.html.erb, app/views/private_labels/user/show.html.erb
Added styling to User settings page
=> Style User Edit

app/views/conversations/_share_buttons.html.erb, app/views/private_labels/conversations/show.html.erb, app/views/private_labels/shared/sidebars/_conversation_share.html.erb
=> Bug/161 Fix Email links on PL and Regular site

app/views/private_labels/search/results.html.erb
- Added text to show no results when searching text
=> Bug/88 Show no results on search

app/views/private_labels/homepage/contact.html.erb
-Blocked map when no address is provided
=> Bug/124 Block Map on Contact without Address

app/views/private_labels/pages/show.html.erb
https://trello.com/c/U7MV0d5Q/113-private-label-static-content-page-1col
- Allowed HTML and embeded objects on coversation
=> Bug/113 Embeded content on Conversation

app/views/private_labels/search/results.html.erb
https://trello.com/c/WOEsdQZb
- Removes empty recent activity sidebar
=> Remove sidebar from search

app/assets/javascripts/private_label/session_status.js.coffee, app/controllers/private_labels/sessions_controller.rb, app/views/private_labels/sessions/status.json.jpbuilder, config/routes.rb
Added the session status route to private label and fixed JS reference to call the right URL. This should keep the browser from constantly loading a missing page.
=> Fixed issue where browser never finishes loading

app/models/issue.rb
https://trello.com/c/gGvkyK85
Sets the issue sort order so that project pages get resorted conversations from most recent to oldest. 
**Note: This PR is to master, this is a product issue, I'll also manually merge to staging**
=> Updated the default order for conversations on an issue

app/controllers/private_labels/subscriptions_controller.rb, app/models/subscription.rb, app/views/private_labels/shared/sidebars/_conversation_share.html.erb, config/routes.rb
Added subscription controller and paths to allow PL subscriptions
=> PL  Follow Error

app/models/activity.rb, npm-debug.log
- https://trello.com/c/2BkmHBSw/225-include-comments-from-remote-pages-on-a-civic-commons-user-s-profile
- Removed restriction on Most Recent Activity that removed remote page contributions
=> Remote Pages in Recent Activiy
